//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOMATI_RADNJE
    {
        public int ID { get; set; }
        public string SIFRA_OBJ { get; set; }
        public string NAZIV { get; set; }
        public string ADRESA { get; set; }
        public Nullable<int> OPSTINA { get; set; }
        public Nullable<int> BROJ_AUTOMATA { get; set; }
        public string JIB { get; set; }
        public string BROJ_TEL { get; set; }
        public Nullable<int> AKTIVAN { get; set; }
    
        public virtual OPCINE OPCINE { get; set; }
    }
}
