//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOMATI_KOMITENTI
    {
        public int ID { get; set; }
        public string OP_BROJ_KOM { get; set; }
        public string JIB { get; set; }
        public int NOSIOC { get; set; }
        public int AKTIVAN { get; set; }
        public Nullable<decimal> POC_STANJE { get; set; }
    }
}
