//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAZNE_IGRE
    {
        public int IGRA_ID { get; set; }
        public Nullable<int> IGRA_AKT { get; set; }
        public string NAZIV { get; set; }
    }
}
