//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EOP_ANA
    {
        public string OPERATIVNI_BROJ { get; set; }
        public string SEDMICA { get; set; }
        public string PRODAJNO_MJESTO { get; set; }
        public string VRIJEME_UPLATE { get; set; }
        public string DATUM_UPLATE { get; set; }
        public string KOLO { get; set; }
        public int ID { get; set; }
        public Nullable<int> KOD_IGRE { get; set; }
        public Nullable<int> INDIKATOR_OBICNI_SISTEMSKI { get; set; }
        public Nullable<decimal> IZNOS_UPLATE { get; set; }
        public Nullable<int> INDIKATOR_STORNA { get; set; }
        public Nullable<int> KOD_LISTICA { get; set; }
    }
}
