//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESRECKE_IGRE
    {
        public int ID { get; set; }
        public Nullable<int> IGRA { get; set; }
        public string NAZIV_IGRE { get; set; }
        public Nullable<decimal> UPLATA { get; set; }
    }
}
