//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GR_ORGANIZACIJE_VIEW
    {
        public string BROBJ { get; set; }
        public string NAZIV { get; set; }
        public string ADRESA { get; set; }
        public string TELEFON { get; set; }
        public string OPIS { get; set; }
    }
}
