//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_ISPLATA
    {
        public int LIS_ID { get; set; }
        public Nullable<int> LIS_GOD { get; set; }
        public Nullable<int> LIS_KOLO { get; set; }
        public string LIS_IGRA { get; set; }
        public string LIS_ISPL { get; set; }
        public string LIS_UPL { get; set; }
        public string LIS_BROJ { get; set; }
        public string LIS_DOB { get; set; }
        public Nullable<int> LIS_BROJD { get; set; }
        public Nullable<decimal> LIS_IZNOSD { get; set; }
        public Nullable<decimal> LIS_IZNOS { get; set; }
        public Nullable<decimal> LIS_POREZ { get; set; }
        public Nullable<System.DateTime> LIS_VRUPL { get; set; }
        public Nullable<System.DateTime> LIS_VRISPL { get; set; }
        public Nullable<int> LIS_UPL_MJE { get; set; }
        public Nullable<int> LIS_ISP_MJE { get; set; }
        public Nullable<int> LIS_TIP_SRE { get; set; }
        public Nullable<int> LIS_SERIJA_SRE { get; set; }
        public string LIS_NAZ_SRE { get; set; }
    }
}
