//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_EOP_ANA
    {
        public string OPERATIVNI_BROJ { get; set; }
        public string SEDMICA { get; set; }
        public string DAN { get; set; }
        public string BROJ_LISTICA { get; set; }
        public string DATUM_UPLATE { get; set; }
        public string VRIJEME_UPLATE { get; set; }
        public string PREPRINT_BROJ { get; set; }
        public string PRODAJNO_MJESTO { get; set; }
        public string KOD_IGRE { get; set; }
        public string KOD_LISTICA { get; set; }
        public string NAZIV_IGRE { get; set; }
        public string INDIKATOR_OBICNI_SISTEMSKI { get; set; }
        public string JOKER_BROJEVI { get; set; }
        public string BINGO_PLUS_BROJEVI { get; set; }
        public string ODIGRANI_BROJEVI { get; set; }
        public string BOJA { get; set; }
        public Nullable<decimal> IZNOS_UPLATE { get; set; }
        public string KOLO { get; set; }
        public string INDIKATOR_STORNA { get; set; }
        public string CHECH_NUM { get; set; }
        public string BROJ_BINGO_KARTICE { get; set; }
        public int ID { get; set; }
    }
}
