//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISPLATA_SINTETIKA
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATUM { get; set; }
        public string OP_BROJ_ISP { get; set; }
        public string SIF_IGRE { get; set; }
        public Nullable<int> TIP_SRECKE { get; set; }
        public Nullable<int> SERIJA { get; set; }
        public string SIF_VRS_DOB { get; set; }
        public Nullable<int> BROJ_DOB { get; set; }
        public Nullable<decimal> IZNOS { get; set; }
        public Nullable<decimal> POREZ { get; set; }
    }
}
