//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KLADIONICA_IGRE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KLADIONICA_IGRE()
        {
            this.KLADIONICA = new HashSet<KLADIONICA>();
            this.PROVJERA_KLADIONICA = new HashSet<PROVJERA_KLADIONICA>();
        }
    
        public int KLAD_ID { get; set; }
        public string KLAD_IGRA { get; set; }
        public Nullable<int> KLAD_SIF { get; set; }
        public Nullable<int> KLAD_AKT { get; set; }
        public Nullable<int> KLAD_KOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KLADIONICA> KLADIONICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVJERA_KLADIONICA> PROVJERA_KLADIONICA { get; set; }
    }
}
