//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class komitenti_ime_matbr_zracun
    {
        public string STARA_SIFRA { get; set; }
        public string IME { get; set; }
        public string PREZIME { get; set; }
        public string OTAC { get; set; }
        public string MJESTO_STANOVANJA { get; set; }
        public string ADRESA { get; set; }
        public string LK { get; set; }
        public string MATICNI_BROJ { get; set; }
        public string OPCINA_STANOVANJA { get; set; }
        public string TELEFON_MOB { get; set; }
        public string TELEFON_FIX { get; set; }
        public string SOC_STATUS { get; set; }
        public string DEMOG_STATUS { get; set; }
        public string SKOL_SPREMA { get; set; }
        public string ORGANIZACIJA { get; set; }
        public string SPOL { get; set; }
        public string ZIRO_RACUN { get; set; }
        public string DEV_RACUN { get; set; }
        public string TELEFON_OLD { get; set; }
        public string TELEFON_DIR { get; set; }
        public string TELEFON_FAX { get; set; }
        public string EMAIL { get; set; }
        public string PORESKI_BROJ { get; set; }
        public string REG_BROJ_FIRME { get; set; }
        public string PR_IME_SUD { get; set; }
        public string ZANIMANJE { get; set; }
        public string TIP_VLASN { get; set; }
        public string KONTAKT { get; set; }
        public string TIP_ORGANIZOVANJA { get; set; }
        public string TIP_ODNOSA { get; set; }
        public string VRSTA_KOMITENTA { get; set; }
        public string DJELATNOST_KOMITENTA { get; set; }
        public string PTT { get; set; }
        public string OPCINA_RODJENJA { get; set; }
        public string BIZNIS_REGISTROVAN { get; set; }
        public string BIZNIS_POSL_PROSTOR { get; set; }
        public Nullable<double> BIZNIS_BROJ_UPOSLENI { get; set; }
        public string DOM_STAM_PROSTOR { get; set; }
        public Nullable<double> DOM_BROJ_CLANOVA { get; set; }
        public Nullable<double> DOM_PRIHODI { get; set; }
        public Nullable<double> DOM_RASHODI { get; set; }
        public string PR_BROJ_UPISA { get; set; }
        public Nullable<System.DateTime> PR_DATUM_OSNIVANJA { get; set; }
        public string KOMITENT { get; set; }
        public string BIZNIS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public string PA_TIP_ORGANIZOVANJA { get; set; }
        public string PA_MATICNI_BROJ { get; set; }
        public string PA_NAZIV { get; set; }
        public string PA_SJEDISTE { get; set; }
        public string PA_ADRESA { get; set; }
        public string PA_DJELATNOST_KOMITENTA { get; set; }
        public string PR_OVLASTENA_OSOBA_JMBG { get; set; }
        public string STATUS { get; set; }
        public string NAPOMENA { get; set; }
        public string ADRESA2 { get; set; }
        public string OPCINA_STANOVANJA2 { get; set; }
        public decimal ID { get; set; }
        public string NACIONALNOST { get; set; }
        public string IZVOR_PRIHODA { get; set; }
        public string VLASNIK_POSLA { get; set; }
        public Nullable<double> SEGMENT_DOMACINSTVA { get; set; }
        public Nullable<double> TIP_DOMACINSTVA { get; set; }
        public string URBANO_RURALNO { get; set; }
        public string STATUS_KOMITENTA { get; set; }
        public string KOMITENT_RIZIK { get; set; }
        public string KOMITENT_SRODSTVO { get; set; }
        public Nullable<System.DateTime> DATUM_RODJENJA { get; set; }
        public string VRSTA_ZADUZENJA { get; set; }
        public string ADRESA_CIPS { get; set; }
        public Nullable<System.DateTime> DATUM_SMRTI { get; set; }
        public string UDIO_VLASNISTVA { get; set; }
        public string UDIO_VLASNISTVA_CLANA_DOM { get; set; }
        public string PR_OVLASTENA_OSOBA_TELEFON { get; set; }
        public string PR_OVLASTENA_OSOBA { get; set; }
        public string NADREDJENI { get; set; }
        public string POREZNI_OBVEZNIK { get; set; }
        public Nullable<System.DateTime> DATUM_VALIDNOSTI_IDDOK { get; set; }
        public string SIFRA_OPCINE_VIRMAN { get; set; }
    }
}
