//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPCINE()
        {
            this.AUTOMATI_RADNJE = new HashSet<AUTOMATI_RADNJE>();
        }
    
        public int OPC_ID { get; set; }
        public string OPC_NAZIV { get; set; }
        public int OPC_KAN { get; set; }
        public string OPC_SIF { get; set; }
        public string BROJ_RACUNA { get; set; }
        public string BROJ_RACUNA1 { get; set; }
        public string VRSTAPRIHODA { get; set; }
        public string PRAVI_NAZIV { get; set; }
        public string PRAVA_SIFRA { get; set; }
        public string POZIV_NA_BROJ { get; set; }
        public int OPC_AKT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTOMATI_RADNJE> AUTOMATI_RADNJE { get; set; }
    }
}
