//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class POC_STANJA
    {
        public int ID { get; set; }
        public Nullable<int> OP_BROJ { get; set; }
        public Nullable<int> MJESEC { get; set; }
        public Nullable<int> GODINA { get; set; }
        public Nullable<decimal> UPLATA_OSN_IGRE { get; set; }
        public Nullable<decimal> UPLATA_KLADIONICA { get; set; }
        public Nullable<decimal> UPLATA_AUTOMATI { get; set; }
        public Nullable<decimal> UPLATA_UKUPNO { get; set; }
        public Nullable<decimal> ISPLATA_OSN_IGRE { get; set; }
        public Nullable<decimal> ISPLATA_KLADIONICA { get; set; }
        public Nullable<decimal> ISPLATA_PAZAR { get; set; }
        public Nullable<decimal> ISPLATA_UKUPNO { get; set; }
        public Nullable<decimal> POC_STANJE { get; set; }
        public Nullable<decimal> TEK_STANJE { get; set; }
    }
}
