//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIJAVA_ORG
    {
        public int ID { get; set; }
        public string KORISNICKO_IME { get; set; }
        public string SIFRA { get; set; }
        public int NIVO { get; set; }
        public int VRSTA { get; set; }
    }
}
