//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVJERA_KLADIONICA
    {
        public int ID { get; set; }
        public Nullable<int> KLAD_IGRA { get; set; }
        public Nullable<System.DateTime> DATUM_IMPORTA { get; set; }
    
        public virtual KLADIONICA_IGRE KLADIONICA_IGRE { get; set; }
    }
}
