//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUCNE_OPERACIJE
    {
        public int ID { get; set; }
        public string OP_BROJ_PROD { get; set; }
        public int VRSTA_OPERACIJE { get; set; }
        public Nullable<System.DateTime> DATUM { get; set; }
        public string KOLO { get; set; }
        public string OPIS { get; set; }
        public Nullable<decimal> IZNOS { get; set; }
        public string KOD_IGRE { get; set; }
        public string TIP_DOKUMENTA { get; set; }
    }
}
