//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRECKE
    {
        public int SRECKA_ID { get; set; }
        public string SRECKA_NAZIV { get; set; }
        public int SRE_AKT { get; set; }
        public Nullable<int> SRE_CIJ { get; set; }
        public Nullable<System.DateTime> SRE_DAT_POC { get; set; }
        public Nullable<System.DateTime> SRE_DAT_ZAV { get; set; }
        public Nullable<int> SRE_EMS { get; set; }
        public Nullable<System.DateTime> SRE_DATPROD { get; set; }
        public Nullable<System.DateTime> SRE_DATROK { get; set; }
        public Nullable<int> SRE_FOND { get; set; }
        public int SRE_SIFRA { get; set; }
        public int SRE_SERIJA { get; set; }
    }
}
