//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLATA
    {
        public int ID { get; set; }
        public Nullable<int> IGRA { get; set; }
        public Nullable<int> OP_BROJ { get; set; }
        public Nullable<int> PROD_MJE { get; set; }
        public Nullable<decimal> IZNOS { get; set; }
        public Nullable<System.DateTime> DATUM { get; set; }
        public Nullable<int> KOLO { get; set; }
        public Nullable<int> KOLO_PRET { get; set; }
    
        public virtual IGRE IGRE { get; set; }
        public virtual UPLATA UPLATA1 { get; set; }
        public virtual UPLATA UPLATA2 { get; set; }
    }
}
