//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZADUZENJE_GOTOVINE
    {
        public int ID { get; set; }
        public int ODOBRITI_BLAGAJNIKA { get; set; }
        public int ZADUZITI_BLAGAJNIKA { get; set; }
        public System.DateTime DATUM { get; set; }
        public Nullable<decimal> IZNOS { get; set; }
        public Nullable<int> AKTIVAN { get; set; }
    }
}
